import { v4 as uuid } from 'uuid'

let inventory = [
  {
    categories: ['upright'], name: 'Kawai U1', price: '12,000', image: '/products/piano1.png', description: 'The K-300 builds upon the success of its award-winning predecessor, the K-3, that was named MMR Magazines Acoustic Piano of the Year for four consecutive years.', brand: 'Kawai Japan', currentInventory: 4 },
  {
    categories: ['spinets'], name: 'Yamaha U1', price: '22,000', image: '/products/piano5.png', description: 'Yamaha came out with their U models in the 1960s, and since then, they have continued to modify and improve the U series. The Yamaha U1 Upright Piano is one of the best-selling (if not the best) pianos in the US and is a popular choice of pianists, teachers, and enthusiasts. Let’s take a closer look at the Yamaha U1 Upright.' , brand: 'Yamaha' , currentInventory: 2 },
  {
    categories: ['upright', 'spinets'], name: 'Boesendorfer U130', price: '64,000', image: '/products/piano6.png', description: 'The Bösendorfer 130 is indeed physically an upright piano, yet, surprises with subtle nuances and the powerful bass of a grand piano. We have transferred refined craftsmanship and our sound philosophy in an upright form to this instrument. The precise action offers freedom in articulation and play with maximum controllability. ', brand: 'Böesendorfer', currentInventory: 8 },
  {
    categories: ['upright', 'spinets'], name: 'Kawai Dark Brown Wood', price: '15,000', image: '/products/piano7.png', description: 'Kawai K200ATX4SLDBWOP Acoustic Upright Piano Silver Fittings Dark Brown Walnut Polish' , brand: 'Kawai Japan', currentInventory: 10},
  {
    categories: ['antique', 'spinets'], name: 'Yamaha 230V Caoba', price: '27,000', image: '/products/piano8.png', description: 'Yamaha Piano - General on take out. The Yamaha u series has long been the first choice in many training centers, for expert professional musicians and amateur pianists. The 121 cm Yamaha U High 1 Piano is characterized by great application force and incomparable lateral characteristics. The Yamaha u 1 features a rich sound with balanced sound character and gleichmäßigem over the entire klaviatur. The Yamaha U 1s special ribbed arrangement gives more strength, while the New Spreizen stop and other strength enhancements, increasing resonance and overall stability. for the Yamaha u de 1 hammers, specially selected materials are used for each model, which provide optimum sound, good sound reproduction and durability. This instrument has been completely redesigned and check that it is regulated by our piano builder before shipping in detail and voted on. We guarantee that this piano will convince its brightness, volume and sound effect totally.', brand: 'Yamaha' , currentInventory: 7 },
  {
    categories: ['on sale', 'spinets'], name: 'Schimmel Upright 55E', price: '12,000', image: '/products/piano9.png', description: 'In the patented Schimmel Konzert Concept, utilised in the Concert series, the well-established and ideal construction concepts for the large Konzert grand piano K 280, have been consistently integrated into the smaller model and, where possible, with identical construction', brand: 'Schimmel', currentInventory: 13},
  {
    categories: ['on sale', 'spinets'], name: 'Sauter Upright Blue Fantasy', price: '30,000', image: '/products/piano10.png', description: 'Sauter pianos are a delight to both player and technician. Beautifully designed and executed, they are among the finest pianos in the world. Theres no skimping on the uprights, either, which are as thoroughly finished as the grands.' , brand: 'Sauter', currentInventory: 9},
  {
    categories: ['spinets', 'antique'], name: 'Shoninger Louis XV', price: '60,000', image: '/products/piano11.png', description: 'The Shoninger Louis XV “Salon” Upright Piano is one of the most elaborate and beautifully carved American upright piano model ever produced. Bernard Shoninger built high quality, expensive pianos from 1850-1929, and the quality and tone of their instruments are known to rival some of the finest brand names ever produced. Shoninger’s Louis XV “Salon” Upright Piano was the highest-grade, most expensive upright piano in the Shoninger product line with a cost at several hundred dollars when new – the cost of a small house!', brand: 'Jason Bourne', currentInventory: 24 },

  {
    categories: ['spinets'], name: 'Steinway and Sons U55', price: '74,000', image: '/products/piano2.png', description: 'Steinway & Sons upright pianos are handcrafted to the highest standard of quality in the same factory as our grands, using the same materials, techniques, conditioning processes and craftsmen. The only difference is that theyre built in the vertical department, where those same processes are vertically oriented.', brand: 'Steinway and Sons Co.', currentInventory: 43 },
  {
    categories: ['upright', 'spinets'], name: 'Ritmüler 120V', price: '22,000', image: '/products/piano3.png', description: 'Ritmüller has been a standard of musical excellence since the name was established in Germany in 1795. Under the auspices of the Pearl River Piano Group, the brand has been raised to an exciting new level of musical quality and virtuosity, European design consultants have specified exquisite Italian styling and fine furniture finishes for each piano in the Ritmüller line. Some features of the brand are truly exceptional. Ritmüller Premium pianos are designed to provide the player with the best touch and tone.', brand: 'Ritmüller' , currentInventory: 2},
  {
    categories: ['on sale', 'antique'], name: 'Bechstein Caoba', price: '30,102', image: '/products/piano4.png', description: 'The upright pianos of the Bechstein Academy Range have also a very lyrical tone, but sound slightly mellower, warmer then the upright pianos of the Residence Range. The Academy uprights and grands of the Bechstein brand are an alternative to the outstanding, but more costly pianos of the Residence Range.', brand: 'Bechstein', currentInventory: 14 },

  {
    categories: ['grand', 'collection'], name: 'Grand Bohemian', price: '490,000', image: '/products/grand1.png', description: 'The Grand Bohemian piano would look as at home in a mythical forest as an art museum or luxury penthouse. A bronze cast base of sculpted tree branches adorn woodland creatures; a majestic peacock with feathers unfurled makes up the music stand. Subtle lighting within the sounding board area and lighting under the rim give the piano an otherworldly glow. Some areas like the frame are gilded with 23-carat finest gold. The vibrant red of the inside of the piano lid and inner rim make this piano unlike any other in elegance and opulence. The “Grand Bohemian” is limited to nine instruments worldwide, this one-of-a-kind masterpiece will be enjoyed by musicians and art aficionados alike.' , brand: 'Boesendorfer', currentInventory: 9 },
  {
    categories: ['on sale', 'grand'], name: "Chopin Collector's Item", price: '180,000', image: '/products/grand2.png', description: 'The Polish piano virtuoso and composer Frédéric Chopin has devoted himself in all his works foremost to piano music. Whether you listen to his mystically thoughtful Nocturnes or his melancholic Waltzes, Chopin allows us a deep glimpse into his soul: affectionate and expressive. On the occasion of his 150th anniversary we created an exclusive instrument to pay tribute to the master of piano compositions. The Bösendorfer Grand Chopin, the gold leaf ornaments and carvings, are inspired by grand pianos Chopin played during his tour in England. They testify to the artistic mastery of the English piano manufacturers of these times who not only were building musical instruments but true pieces of art. The fall board is decorated with an engraved, gilded plaque bearing Chopin’s signature. Masterly.' , brand: 'Boesendorfer', currentInventory: 13},
  {
    categories: ['on sale', 'grand'], name: 'Ceni Matte Oranve', price: '290,000', image: '/products/grand3.png', description: 'The Italian composer, conductor and pianist Ferruccio Busoni meticulously transcribes the famous organ works of J.S. Bach. He soon realises that he requires additional bass notes in order to do Bach’s masterpieces and the immersive sound of 16 to 32 feet bass pipes found in an organ justice. Ludwig Bösendorfer is ready to take on the challenge and builds the first prototype having full 8 octaves in tonal range. Not only Busoni starts to appreciate the exceptional qualities of the – later coined – Imperial Concert Grand: Bartók, Debussy and Ravel compose further works to exploit the tremendous resonance of this very instrument. These oeuvres can only played and interpreted as they were meant to on this Concert Grand. Evoking an extraordinary sound – sonorous and rich in expression and resonance – the timbre of the Imperial Grand seems to be orchestral. The additional deeper bass notes resonate with every key you strike and the massive soundboard supports the projection of any frequency. Ludwig Bösendorfer’s Imperial still to this day represents the precious heritage of the Bösendorfer piano manufactory. Impressive in sound, imposing in appearance.' , brand: 'Boesendorfer', currentInventory: 2},
  {
    categories: ['on sale', 'grand'], name: 'Abisko Green Recliner', price: '200,000', image: '/products/grand4.png', description: 'The SPIRIO | r is the world’s finest high resolution player piano and is also capable of high resolution acoustic recording, editing and playback. At 8 11¾ (274 cm) in length, the majestic Model D is the pinnacle of concert grands and the overwhelming choice of the world’s greatest pianists and for anyone who demands the highest level of music expression.  Complimentary iPad Pro® included.', brand: 'Steinway and Sons', currentInventory: 23 },

  { categories: ['on sale', 'collection', 'grand'], name: "Baroque Collector's item", price: '250,000', image: '/products/grand5.png', description: ' At the end of the 16 century, a new movement in art spreads quickly across Europe and eventually reaches Austria. It is the dawn of the Baroque. In music, the virtuous compositions of Johann Sebastian Bach are about to create controversy: in fine arts spectators are about to gaze in astonishment at sumptuous splendour in visual expressions and architecture. Bright colours fancy playfully carved lines, gilded frames and sculptural figures. Grand and opulent in expression.Manufactured over countless hours by our artisans the Bösendorfer Baroque is one of our most extravagant designs. Sophisticated decorations perfect the Ivory coloured satin silhouette of the piano, the individually carved legs, as well as the lavish use of gold, showing the artisan’s loving eye for detail. ' , brand: 'Boesendorfer', currentInventory: 13},
  
  { categories: ['grand', 'collection'], name: "Liszt Collector's item", price: '190,899', image: '/products/grand6.png', description: 'When Ignaz Bösendorfer started his own piano manufacturing company the young virtuoso Franz Liszt is ruining almost every piano with his passionate playing. At this time, there are nearly 150 piano builders in Vienna alone, which actually illustrates the importance of piano music. Following the advice of his friends Liszt selects a Bösendorfer Grand for his concert and, in fact, this piano withstands his powerful performance. Bösendorfer becomes famous overnight. A close friendship shall evolve between Franz Liszt and Bösendorfer. This Bösendorfer Grand, crafted with precious Vavona veneer, is a tribute to this exceptionally talented, pianist and composer, who himself owned quite a few Bösendorfer Grands. The close relation with Bösendorfer is documented by more than 40 letters and telegrams written by Liszt. Pianists have always found a reliable partner in a Bösendorfer Grand. Artists do not have to limit their virtuoso play in any way and may unleash their artistic play freely. Like Liszt once did.', brand: 'Boesendorfer', currentInventory: 15 },

  { categories: ['on sale', 'collection'], name: 'Secession Grand', price: '230,049', image: '/products/grand7.png', description: 'The Bösendorfer Secession Grand takes up this symbol of bay leaves in ornamented form from the façade. Gold-plated with 23-carat gold, the leaves on the inside of the lid shine, as does the gold-plated cast iron frame. The inside walls of the case and the pin block take up the delicate green colour of the bay leaves from the cupola. The motto Ver Sacrumis engraved in the music stand letter by letter and likewise gold-plated with 23-carat gold. The edge of the lid and the pedal box are rimmed with gold-plated lines done by hand. The model Secession captivates in size 214VC Vienna Concert Grand with brilliant sound and sheer inexhaustible tone colours. ', brand: 'Boesendorfer', currentInventory: 2 },
  
  { categories: ['grand', 'collection'], name: 'Marco Polo Fazioli', price: '150,030', image: '/products/grand8.png', description: 'This example of a specifically commissioned piano features an unusual red high gloss varnish with a hand-painted reproduction of a Canaletto painting… which celebrates the ancient connection between Venice and China: the clients country.', brand: 'Fazioli', currentInventory: 17 },
  
  { categories: ['grand', 'collection'], name: 'African Wood Steinway D', price: '135,973', image: '/products/grand9.png', description: 'The STEINWAY CROWN JEWEL COLLECTION is an exclusive series of spectacular STEINWAYS that feature particularly fine veneers. High-quality Mahogany, Walnut, Kewazinga Bubinga, East Indian Rosewood, Macassar Ebony, and other veneers are available.', brand: 'Steinway and Sons', currentInventory: 28 },
  
  { categories: ['grand', 'collection'], name: 'Pop Collection Steinway and Sons', price: '120,530', image: '/products/grand10.png', description: 'The STEINWAY COLOR COLLECTION offers a fresh take on the classic STEINWAY. Vibrantly colorful accents breathe character into an ebony grand. A rainbow of fully customizable colors make this special collection STEINWAY an exciting choice to express personality, individuality, and style.', brand: 'Steinway and sons', currentInventory: 31 },  // { 
]

inventory.map(i => {
  i.id = uuid()
  return i
})

export default inventory